### PR TITLE
Correctly identify main file for bower.

### PR DESCRIPTION
**Pull request by RQuadling**
No longer using ```dist```, but ```src```.

### CODE REVIEW

**Comment by RQuadling** [comment]
Can this be merged please?

**Comment by codeimpossible** [comment]
dist is the correct file for bower - or at least it should be. Take a look at the tag for [v1.4.0](https://github.com/digitalBush/jquery.maskedinput/tree/1.4.0/dist). Did the bower install not work for you?

**Comment by RQuadling** [comment]
In https://github.com/digitalBush/jquery.maskedinput/blob/305e9af609ee5bdd650d703fe53f0c093f77a4ee/bower.json, there is no "main" entry, so bower-installer won't work. And master has no dist, so sort of stuck in the middle.

**Comment by TrySound** [comment]
Why remove dist folder not for tags? Just confusing.

**Comment by RQuadling** [comment]
And that version has the false upper limit for jQuery.

So need a new tag/release that has the removal of the upper jQuery version, has a "main" entry in bower.json.

**Comment by TrySound** [comment]
It is very necessary.

**Comment by RQuadling** [comment]
OK. Then I think all we need is a new tagged release, rather than pulling from master and building our own release.

**Comment by digitalBush** [comment]
Ahhh, the main field was added after the 1.4.0 drop it seems. I just pushed 1.4.1, please let me know if that looks right.

**Comment by RQuadling** [comment]
Perfect. Thank you.

**Pull request closed without merging**
