### PR TITLE
code cosmetics

### PR DESCRIPTION
**Pull request by JBlond**
Just a bit code cosmetics

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
You may also add `grunt-contrib-jshint` and `grunt-contrib-jscs` to enforce consistency and prevent future PRs of this kind.

**Comment by vsn4ik** [comment]
:+1: for merge.

**Comment by jt3k** [comment]
fix all tests !

**Comment by JBlond** [comment]
Tests fixed.
Even tho it doesn't seem to be logical to have the code that way how it is done by digitalBush

**Pull request closed without merging**
